add tests for native crypto

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -14,40 +14,46 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Install xmlstarlet
-      run: sudo apt-get update && sudo apt-get install -y xmlstarlet
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: 8.0.x
-    - name: Restore dependencies
-      run: dotnet restore
-    - name: Check code formatting
-      run: |
-        dotnet tool install --global dotnet-format
-        dotnet format --verify-no-changes
-    - name: Build
-      run: dotnet build --no-restore
-    - name: Test
-      run: ./scripts/testwithcoverage.sh
-    - name: Filter coverage reports to remove empty packages
-      run: find ./coverage -name 'coverage.cobertura.xml' -exec xmlstarlet ed -L -d "//package[not(classes/class)]" {} \;
-    - name: Code Coverage Report
-      uses: irongut/CodeCoverageSummary@v1.3.0
-      with:
-        filename: coverage/**/coverage.cobertura.xml
-        badge: true
-        fail_below_min: false
-        format: markdown
-        hide_branch_rate: false
-        hide_complexity: true
-        indicators: true
-        output: both
-        thresholds: '60 80'
-    - name: Upload Artifacts
-      uses: actions/upload-artifact@v3  # upload test results
-      if: success() || failure()        # run this step even if previous step failed
-      with:
-        name: test-results
-        path: coverage/test-results.trx
+      - uses: actions/checkout@v4
+      - name: Install xmlstarlet
+        run: sudo apt-get update && sudo apt-get install -y xmlstarlet
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: 8.0.x
+      - name: Restore dependencies
+        run: dotnet restore
+      - name: Check code formatting
+        run: |
+          dotnet tool install --global dotnet-format
+          dotnet format --verify-no-changes
+      - name: Build
+        run: dotnet build --no-restore
+      - name: Test
+        run: ./scripts/testwithcoverage.sh
+      - name: Filter coverage reports to remove empty packages
+        run: find ./coverage -name 'coverage.cobertura.xml' -exec xmlstarlet ed -L -d "//package[not(classes/class)]" {} \;
+      - name: Code Coverage Report
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: coverage/**/coverage.cobertura.xml
+          badge: true
+          fail_below_min: false
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: true
+          indicators: true
+          output: both
+          thresholds: '60 80'
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: coverage/test-results.trx
+      - name: Build for Native Crypto
+        if: success()
+        run: dotnet build -c Release.Native
+      - name: Test
+        if: success()
+        run: ./scripts/testwithcoverage.sh "Release.Native"
